In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('customer.csv')

In [18]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

### Ordinal encoding: Encoding for features where order matters.

#### Ex. Education: School, College and Graduation => 0, 1 and 3 respectively

In [21]:
df_cate = df.iloc[:,2:4]
df_cate.head()

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

In [5]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(df_cate, df['purchased'],test_size=0.2,random_state=42)

In [14]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [15]:
X_train_encoded=oe.fit_transform(X_train)

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [23]:
X_train.head()

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG

In [19]:
X_train_encoded

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [28]:
X_train = pd.DataFrame(data=X_train_encoded,columns=['review','education'],dtype=int)

In [29]:
X_train.head()

   review  education
0       0          0
1       1          1
2       1          2
3       1          1
4       2          2

In [33]:
X_test_encoded = oe.transform(X_test)

In [34]:
X_test_encoded

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

In [35]:
X_test = pd.DataFrame(data=X_test_encoded,columns=['review','education'],dtype=int)

In [36]:
X_test.head()

   review  education
0       1          0
1       0          2
2       1          1
3       0          2
4       0          1