# Working with json

In [1]:
import pandas as pd

In [2]:
pd.read_json('train.json').head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.0405
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.6910
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.8970
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,4.1600
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,2.6300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.1770
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.2050
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.2820

#### Note : Most of read_csv parameters will also work with read_json as well

# Working with sql

In [4]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 6.7 MB/s eta 0:00:02
     ------- -------------------------------- 2.1/11.9 MB 7.3 MB/s eta 0:00:02
     ------------ --------------------------- 3.7/11.9 MB 7.0 MB/s eta 0:00:02
     ---------------- ----------------------- 5.0/11.9 MB 7.0 MB/s eta 0:00:01
     ------------------- -------------------- 5.8/11.9 MB 6.5 MB/s eta 0:00:01
     -------------------- ------------------- 6.0/11.9 MB 5.8 MB/s eta 0:00:02
     ---------------------- ----------------- 6.6/11.9 MB 4.7 MB/s eta 0:00:02
     ----------------------- ---------------- 6.8/11.9 MB 4.5 MB/s eta 0:00:02
     ----------------------- ---------------- 7.1/11.9 MB 4.3 MB/s eta 0:00:02
     ------------------------ --------------- 7.3/11.9 MB 3.9 MB/s eta 0:00:02
     ------------------------- -------------- 7.6/11.9 MB 3.6 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 3.3 MB/s eta 0:00:02
     ---------------------------- ----------- 8.4/11.9 MB 3.3 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 3.2 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 3.2 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 3.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 3.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.1 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 3.1 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.0 MB/s  0:00:04
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=248049 sha256=1d54bdf6182e26c4f93df51f57a93c8d3f6dee76409acb3c6f444baaf7dfffe2
  Stored in directory: c:\users\91939\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import mysql.connector

In [7]:
#conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [8]:
#df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)
#df

#### Note: Make sure to start apache and mysql server in XMAPP